"""
Download large-scale frontend code data from The Stack v2 (HuggingFace).
This provides enough data for training 1B+ parameter models.

Target: ~2-5GB of filtered frontend code = ~600M-1.5B BPE tokens
With modest repetition (3-5x), enough for a 1B model.

Prerequisites:
  1. Create a HuggingFace account: https://huggingface.co/join
  2. Accept The Stack v2 terms: https://huggingface.co/datasets/bigcode/the-stack-v2
  3. Install: pip install datasets huggingface_hub
  4. Login: huggingface-cli login

Usage:
  python scripts/get_stack_data.py                    # default ~2GB target
  python scripts/get_stack_data.py --target-gb 5      # larger download
  python scripts/get_stack_data.py --languages ts,tsx  # specific languages only
"""

import os
import sys
import json
import hashlib
from pathlib import Path

os.environ["PYTHONUNBUFFERED"] = "1"
import builtins
_original_print = builtins.print
builtins.print = lambda *args, **kwargs: _original_print(*args, **{**kwargs, "flush": True})

OUTPUT_DIR = Path(__file__).parent.parent / "data" / "stack-frontend"

# Languages to include and their approximate share of the dataset
FRONTEND_LANGUAGES = {
    "TypeScript":   0.30,  # primary focus
    "TSX":          0.20,  # React components
    "JavaScript":   0.25,  # JS ecosystem
    "JSX":          0.05,  # React JS components
    "CSS":          0.10,  # styling
    "HTML":         0.10,  # markup
}

# Content filters (same as our other scripts)
SKIP_PATTERNS = [
    "node_modules", "dist/", "build/", ".next/", "coverage/",
    ".min.", "vendor/", ".bundle.",
    "package-lock", "yarn.lock", "pnpm-lock",
]

AUTO_GENERATED_MARKERS = [
    "auto-generated", "AUTO GENERATED", "DO NOT EDIT",
    "Generated by", "This file was generated", "codegen",
    "eslint-disable", "prettier-ignore",  # full-file disables suggest generated
]

SVG_PATTERNS = ["<svg", "<path", ' d="M', "viewBox="]


def check_prerequisites():
    """Check that HuggingFace is set up."""
    try:
        import datasets
        from huggingface_hub import HfApi
        api = HfApi()
        user = api.whoami()
        print(f"  HuggingFace user: {user.get('name', 'unknown')}")
        return True
    except ImportError:
        print("  Install required packages:")
        print("    pip install datasets huggingface_hub")
        return False
    except Exception as e:
        print(f"  HuggingFace auth error: {e}")
        print("  Run: huggingface-cli login")
        return False


def passes_quality_filter(content, path=""):
    """Check if a file passes quality filters."""
    # Size
    if len(content) < 50 or len(content) > 100_000:
        return False

    # Skip patterns in path
    path_lower = path.lower()
    if any(p in path_lower for p in SKIP_PATTERNS):
        return False

    # Auto-generated
    header = content[:500]
    if any(m in header for m in AUTO_GENERATED_MARKERS):
        return False

    # SVG data
    svg_count = sum(content.count(p) for p in SVG_PATTERNS)
    if svg_count > 5:
        return False

    # Mostly whitespace or comments
    lines = content.split("\n")
    non_empty = [l for l in lines if l.strip()]
    if len(non_empty) < 3:
        return False

    comment_lines = sum(1 for l in non_empty
                       if l.strip().startswith("//") or l.strip().startswith("*")
                       or l.strip().startswith("/*"))
    if len(non_empty) > 0 and comment_lines / len(non_empty) > 0.7:
        return False

    return True


def download_language(language, target_files, output_path):
    """Download and filter files for one language from The Stack."""
    from datasets import load_dataset

    print(f"\n  Downloading {language}...")
    print(f"  Target: {target_files:,} files")

    try:
        # The Stack v2 can be streamed to avoid downloading everything
        dataset = load_dataset(
            "bigcode/the-stack-v2-dedup",
            data_dir=f"data/{language}",
            split="train",
            streaming=True,
        )
    except Exception as e:
        print(f"  Error loading {language}: {e}")
        print(f"  (This language may not be available or terms not accepted)")
        return 0

    count = 0
    total_chars = 0
    skipped = 0

    with open(output_path, "a", encoding="utf-8") as f:
        for item in dataset:
            if count >= target_files:
                break

            content = item.get("content", "")
            path = item.get("path", "")

            if not passes_quality_filter(content, path):
                skipped += 1
                continue

            f.write(f"// FILE: {path}\n")
            f.write(content)
            f.write("\n\n")

            count += 1
            total_chars += len(content)

            if count % 1000 == 0:
                print(f"    {count:,} files, {total_chars/1_000_000:.1f}MB, skipped {skipped:,}")

    print(f"    Done: {count:,} files, {total_chars/1_000_000:.1f}MB (skipped {skipped:,})")
    return total_chars


def main():
    target_gb = 2.0
    languages = None

    for i, arg in enumerate(sys.argv[1:], 1):
        if arg == "--target-gb" and i < len(sys.argv) - 1:
            target_gb = float(sys.argv[i + 1])
        if arg == "--languages" and i < len(sys.argv) - 1:
            languages = sys.argv[i + 1].split(",")

    target_chars = int(target_gb * 1_000_000_000)

    print("=" * 60)
    print("  Download Frontend Data from The Stack v2")
    print("=" * 60)
    print(f"  Target: ~{target_gb}GB of filtered frontend code")
    print(f"  Estimated BPE tokens: ~{target_chars/3.4/1_000_000:.0f}M")
    print()

    # Check prerequisites
    print("Checking prerequisites...")
    if not check_prerequisites():
        sys.exit(1)
    print()

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    output_path = OUTPUT_DIR / "corpus.txt"

    # Clear existing file
    if output_path.exists():
        print(f"  Removing existing corpus: {output_path}")
        output_path.unlink()

    # Calculate per-language targets
    lang_list = languages or list(FRONTEND_LANGUAGES.keys())
    total_chars = 0

    print(f"Languages: {', '.join(lang_list)}")

    for lang in lang_list:
        share = FRONTEND_LANGUAGES.get(lang, 0.1)
        lang_target_chars = int(target_chars * share)
        # Rough estimate: average file is ~2000 chars
        target_files = lang_target_chars // 2000

        chars = download_language(lang, target_files, output_path)
        total_chars += chars

    # Final stats
    est_tokens = total_chars / 3.4
    print()
    print("=" * 60)
    print("  Download Complete")
    print("=" * 60)
    print(f"  Corpus: {output_path}")
    print(f"  Size: {total_chars/1_000_000:.0f}MB ({total_chars/1_000_000_000:.1f}GB)")
    print(f"  Estimated BPE tokens: ~{est_tokens/1_000_000:.0f}M")
    print()
    print(f"  For 100M model (needs ~2B tokens): {'sufficient' if est_tokens > 500_000_000 else 'need more data or repetition'}")
    print(f"  For 1B model (needs ~20B tokens): {'sufficient' if est_tokens > 5_000_000_000 else 'will need repetition (' + str(int(20_000_000_000/max(est_tokens,1))) + 'x)'}")
    print()
    print("  Next steps:")
    print("    python scripts/train_tokenizer.py --corpus data/stack-frontend/corpus.txt")
    print("    Upload to GitHub release for cloud training")


if __name__ == "__main__":
    main()
