"""
Download expanded frontend training data.
Adds more repos and includes HTML/CSS files alongside TypeScript/TSX.

This gives us enough data for 100M+ parameter models.

Usage: python scripts/get_expanded_data.py
"""

import os
import subprocess
import shutil
from pathlib import Path

# Expanded repo list — more repos, broader frontend coverage
REPOS = [
    # Component libraries (high quality React/TS)
    ("shadcn-ui/ui", "shadcn-ui"),
    ("radix-ui/primitives", "radix-primitives"),
    ("mantinedev/mantine", "mantine"),
    ("chakra-ui/chakra-ui", "chakra-ui"),
    ("tremor-so/tremor", "tremor"),
    ("nextui-org/nextui", "nextui"),
    ("ariakit/ariakit", "ariakit"),
    ("primefaces/primereact", "primereact"),

    # Full apps (real-world patterns)
    ("calcom/cal.com", "calcom"),
    ("vercel/next.js", "nextjs"),
    ("trpc/trpc", "trpc"),
    ("steven-tey/novel", "novel"),
    ("sadmann7/skateshop", "skateshop"),
    ("vercel/commerce", "vercel-commerce"),
    ("vercel/platforms", "vercel-platforms"),
    ("t3-oss/create-t3-app", "create-t3"),
    ("dubinc/dub", "dub"),
    ("formbricks/formbricks", "formbricks"),
    ("documenso/documenso", "documenso"),

    # State management / hooks / utilities
    ("TanStack/query", "tanstack-query"),
    ("TanStack/table", "tanstack-table"),
    ("TanStack/router", "tanstack-router"),
    ("pmndrs/zustand", "zustand"),
    ("pmndrs/jotai", "jotai"),
    ("react-hook-form/react-hook-form", "react-hook-form"),

    # CSS / styling focused
    ("tailwindlabs/tailwindcss", "tailwindcss"),
    ("tailwindlabs/headlessui", "headlessui"),
    ("nativewind/nativewind", "nativewind"),

    # Framework / tooling
    ("vitejs/vite", "vite"),
    ("remix-run/remix", "remix"),
    ("solidjs/solid", "solid"),
]

RAW_DIR = Path(__file__).parent.parent / "data" / "react-ts-expanded" / "repos"
OUTPUT_FILE = Path(__file__).parent.parent / "data" / "react-ts-expanded" / "corpus.txt"

# Include HTML and CSS alongside TS/TSX
EXTENSIONS = {".ts", ".tsx", ".jsx", ".css", ".html", ".htm"}

SKIP_PATTERNS = [
    "node_modules", "dist", "build", ".next", "coverage",
    "__tests__", "test", "spec", ".d.ts", "package-lock",
    ".min.", "vendor", "jest", "cypress",
    ".svg", "icon",                           # SVG path data
    "migration", "seed",                      # database
    "fixture", "mock", "__mock__",            # test fixtures
    "generated", "codegen",                   # auto-generated
    ".stories.", "storybook",                 # Storybook
    "locale", "i18n", "translation", "lang",  # translations
    ".snap",                                  # Jest snapshots
    "CHANGELOG", "changelog",                 # changelogs
]


def clone_repo(repo, name, target_dir):
    dest = target_dir / name
    if dest.exists():
        print(f"  Already cloned: {name}")
        return dest

    print(f"  Cloning {repo}...")
    try:
        subprocess.run(
            ["git", "clone", "--depth", "1", "--single-branch",
             f"https://github.com/{repo}.git", str(dest)],
            capture_output=True, text=True, timeout=180,
        )
    except subprocess.TimeoutExpired:
        print(f"  Timeout cloning {repo}, skipping")
        if dest.exists():
            shutil.rmtree(dest)
        return None

    git_dir = dest / ".git"
    if git_dir.exists():
        shutil.rmtree(git_dir)

    return dest


def should_skip(filepath):
    path_str = str(filepath).lower()
    return any(pattern in path_str for pattern in SKIP_PATTERNS)


def has_svg_data(content):
    """Check if content is mostly SVG path data."""
    svg_indicators = ["<svg", "<path", ' d="M', "viewBox="]
    count = sum(content.count(p) for p in svg_indicators)
    return count > 5


def has_auto_generated_marker(content):
    """Check for auto-generated file markers."""
    markers = ["auto-generated", "AUTO GENERATED", "DO NOT EDIT",
               "Generated by", "This file was generated", "codegen"]
    header = content[:500]
    return any(m in header for m in markers)


def extract_files(repo_dir, name):
    files = []
    for ext in EXTENSIONS:
        for filepath in repo_dir.rglob(f"*{ext}"):
            if should_skip(filepath):
                continue
            try:
                content = filepath.read_text(encoding="utf-8")

                # Size filters
                if len(content) < 50:
                    continue
                if len(content) > 50_000:
                    continue
                if content.count("\n") < 3:
                    continue

                # Content filters
                if has_svg_data(content):
                    continue
                if has_auto_generated_marker(content):
                    continue

                files.append((name, str(filepath.relative_to(repo_dir)), content))
            except (UnicodeDecodeError, OSError):
                continue

    return files


def build_corpus(all_files, output_path):
    print(f"\nBuilding corpus from {len(all_files):,} files...")

    total_chars = 0
    with open(output_path, "w", encoding="utf-8") as f:
        for repo_name, filepath, content in all_files:
            header = f"// FILE: {filepath}\n"
            f.write(header)
            f.write(content)
            f.write("\n\n")
            total_chars += len(header) + len(content) + 2

    print(f"Corpus written to: {output_path}")
    print(f"Total size: {total_chars:,} characters ({total_chars/1_000_000:.1f}MB)")
    return total_chars


def main():
    print("=" * 60)
    print("  Downloading Expanded Frontend Training Data")
    print("  (React/TS + HTML + CSS)")
    print("=" * 60)
    print()

    RAW_DIR.mkdir(parents=True, exist_ok=True)

    # Clone repos
    print(f"Step 1: Cloning {len(REPOS)} repos...")
    repo_dirs = []
    for repo, name in REPOS:
        result = clone_repo(repo, name, RAW_DIR)
        if result:
            repo_dirs.append((result, name))
    print()

    # Extract files
    print("Step 2: Extracting frontend files (TS/TSX/JSX/CSS/HTML)...")
    all_files = []
    ext_counts = {}
    for repo_dir, name in repo_dirs:
        files = extract_files(repo_dir, name)
        print(f"  {name}: {len(files)} files")
        all_files.extend(files)
        for _, path, _ in files:
            ext = Path(path).suffix.lower()
            ext_counts[ext] = ext_counts.get(ext, 0) + 1

    print(f"\nTotal: {len(all_files):,} files")
    print(f"By type:")
    for ext, count in sorted(ext_counts.items(), key=lambda x: -x[1]):
        print(f"  {ext}: {count:,}")

    # Build corpus
    print("\nStep 3: Building training corpus...")
    total_chars = build_corpus(all_files, OUTPUT_FILE)

    # Stats
    print()
    print("=" * 60)
    print("  Summary")
    print("=" * 60)
    print(f"  Repos cloned: {len(repo_dirs)}")
    print(f"  Files extracted: {len(all_files):,}")
    print(f"  Corpus size: {total_chars:,} chars ({total_chars/1_000_000:.1f}MB)")
    print(f"  Output: {OUTPUT_FILE}")

    # Estimate token counts
    est_tokens = total_chars / 3.4  # approximate BPE compression
    print(f"  Estimated BPE tokens: ~{est_tokens/1_000_000:.0f}M")
    print()

    # Cleanup repos to save disk
    print("  Cleaning up raw repos to save disk space...")
    shutil.rmtree(RAW_DIR)
    print("  Done!")


if __name__ == "__main__":
    main()
