"""
Download frontend code data from StarCoderData (HuggingFace).
This is The Stack v1 pre-filtered for StarCoder — already deduped and cleaned.
Contains actual code content, supports streaming.

Target: ~1.5GB of filtered frontend code = ~450M BPE tokens

Prerequisites:
  1. Create a HuggingFace account: https://huggingface.co/join
  2. Accept terms: https://huggingface.co/datasets/bigcode/starcoderdata
  3. pip install datasets huggingface_hub
  4. huggingface-cli login

Usage:
  python scripts/get_stack_data.py                    # default ~1.5GB target
  python scripts/get_stack_data.py --target-gb 0.5    # smaller download
  python scripts/get_stack_data.py --target-gb 3      # larger download
  python scripts/get_stack_data.py --test              # tiny test (10MB) to verify it works
"""

import os
import sys
import time
from pathlib import Path

os.environ["PYTHONUNBUFFERED"] = "1"
import builtins
_original_print = builtins.print
builtins.print = lambda *args, **kwargs: _original_print(*args, **{**kwargs, "flush": True})

OUTPUT_DIR = Path(__file__).parent.parent / "data" / "stack-frontend"

# Languages and their share of our target
FRONTEND_LANGUAGES = [
    ("typescript", 0.35),
    ("javascript", 0.30),
    ("css", 0.15),
    ("html", 0.20),
]

# Content filters
SKIP_PATTERNS = [
    "node_modules", "dist/", "build/", ".next/", "coverage/",
    ".min.", "vendor/", ".bundle.", "package-lock", "yarn.lock",
]

AUTO_GENERATED_MARKERS = [
    "auto-generated", "AUTO GENERATED", "DO NOT EDIT",
    "Generated by", "This file was generated",
]

SVG_PATTERNS = ["<svg", "<path", ' d="M', "viewBox="]


def check_prerequisites():
    """Check that HuggingFace is set up."""
    try:
        from datasets import load_dataset
        from huggingface_hub import HfApi
        api = HfApi()
        user = api.whoami()
        print(f"  HuggingFace user: {user.get('name', 'unknown')}")
        return True
    except ImportError:
        print("  Install required packages:")
        print("    pip install datasets huggingface_hub")
        return False
    except Exception as e:
        print(f"  HuggingFace auth error: {e}")
        print("  Run: huggingface-cli login")
        return False


def passes_filter(content, path=""):
    """Check if a file passes quality filters."""
    if not content or len(content) < 50 or len(content) > 100_000:
        return False

    path_lower = path.lower()
    if any(p in path_lower for p in SKIP_PATTERNS):
        return False

    header = content[:500]
    if any(m in header for m in AUTO_GENERATED_MARKERS):
        return False

    svg_count = sum(content.count(p) for p in SVG_PATTERNS)
    if svg_count > 5:
        return False

    lines = content.split("\n")
    non_empty = [l for l in lines if l.strip()]
    if len(non_empty) < 3:
        return False

    return True


def download_language(lang_name, target_chars, output_file):
    """Stream and filter files for one language."""
    from datasets import load_dataset

    print(f"\n  Streaming {lang_name}...")
    print(f"  Target: {target_chars / 1_000_000:.0f}MB")

    try:
        dataset = load_dataset(
            "bigcode/starcoderdata",
            data_dir=lang_name,
            split="train",
            streaming=True,
        )
    except Exception as e:
        print(f"  Error loading {lang_name}: {e}")
        return 0

    count = 0
    total_chars = 0
    skipped = 0

    with open(output_file, "a", encoding="utf-8") as f:
        for item in dataset:
            if total_chars >= target_chars:
                break

            content = item.get("content", "")
            path = item.get("path", item.get("id", ""))

            if not passes_filter(content, path):
                skipped += 1
                continue

            f.write(f"// FILE: {path}\n")
            f.write(content)
            f.write("\n\n")

            count += 1
            total_chars += len(content)

            if count % 2000 == 0:
                mb = total_chars / 1_000_000
                print(f"    {count:,} files, {mb:.1f}MB, skipped {skipped:,}")

    mb = total_chars / 1_000_000
    print(f"    Done: {count:,} files, {mb:.1f}MB (skipped {skipped:,})")
    return total_chars


def run_sanity_checks(output_file):
    """Verify the downloaded data looks correct."""
    print("\n  Running sanity checks...")

    text = open(output_file).read()
    total_chars = len(text)
    total_lines = text.count("\n")
    file_count = text.count("// FILE:")

    print(f"    Total size: {total_chars / 1_000_000:.1f}MB")
    print(f"    Total lines: {total_lines:,}")
    print(f"    Total files: {file_count:,}")

    # Check a few random files
    files = text.split("// FILE: ")
    if len(files) > 1:
        import random
        samples = random.sample(files[1:], min(5, len(files) - 1))
        print(f"\n    Sample files:")
        for sample in samples:
            first_line = sample.split("\n")[0][:80]
            content_lines = len(sample.split("\n"))
            has_code = any(kw in sample[:500] for kw in ["function", "const", "import", "class", "<div", "{", "export"])
            print(f"      {first_line}  ({content_lines} lines, {'has code' if has_code else 'NO CODE'})")

    # Check for obvious problems
    problems = []
    if total_chars < 1_000_000:
        problems.append("Very small corpus (<1MB)")
    if file_count < 100:
        problems.append("Very few files (<100)")

    # Check language distribution
    ts_count = text.count(".ts\n") + text.count(".tsx\n")
    js_count = text.count(".js\n") + text.count(".jsx\n")
    css_count = text.count(".css\n")
    html_count = text.count(".html\n")
    print(f"\n    Language distribution (approximate):")
    print(f"      TypeScript: ~{ts_count:,} files")
    print(f"      JavaScript: ~{js_count:,} files")
    print(f"      CSS: ~{css_count:,} files")
    print(f"      HTML: ~{html_count:,} files")

    # Check for SVG contamination
    svg_lines = sum(1 for line in text.split("\n") if '<path d="M' in line)
    if svg_lines > 100:
        problems.append(f"SVG contamination: {svg_lines} lines with path data")

    if problems:
        print(f"\n    WARNINGS:")
        for p in problems:
            print(f"      ! {p}")
    else:
        print(f"\n    All checks passed!")

    return len(problems) == 0


def main():
    target_gb = 1.5
    test_mode = False

    for i, arg in enumerate(sys.argv[1:], 1):
        if arg == "--target-gb" and i < len(sys.argv) - 1:
            target_gb = float(sys.argv[i + 1])
        if arg == "--test":
            test_mode = True
            target_gb = 0.01  # 10MB test

    target_chars = int(target_gb * 1_000_000_000)

    print("=" * 60)
    print("  Download Frontend Data from StarCoderData")
    print("=" * 60)
    if test_mode:
        print(f"  TEST MODE: downloading ~10MB to verify pipeline")
    else:
        print(f"  Target: ~{target_gb}GB of filtered frontend code")
    print()

    # Check prerequisites
    print("Checking prerequisites...")
    if not check_prerequisites():
        sys.exit(1)
    print()

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    output_file = OUTPUT_DIR / "corpus.txt"

    # Clear existing
    if output_file.exists():
        if test_mode:
            output_file.unlink()
        else:
            existing_size = output_file.stat().st_size
            print(f"  Existing corpus: {existing_size / 1_000_000:.0f}MB")
            response = input("  Delete and redownload? (y/N): ").strip().lower()
            if response != 'y':
                print("  Keeping existing. Exiting.")
                return
            output_file.unlink()

    total_chars = 0

    for lang_name, share in FRONTEND_LANGUAGES:
        lang_target = int(target_chars * share)
        chars = download_language(lang_name, lang_target, str(output_file))
        total_chars += chars

        if test_mode and total_chars > target_chars:
            break

    # Sanity checks
    ok = run_sanity_checks(str(output_file))

    # Summary
    est_tokens = total_chars / 3.4
    print()
    print("=" * 60)
    print("  Download Complete")
    print("=" * 60)
    print(f"  Corpus: {output_file}")
    print(f"  Size: {total_chars / 1_000_000:.0f}MB ({total_chars / 1_000_000_000:.1f}GB)")
    print(f"  Estimated BPE tokens: ~{est_tokens / 1_000_000:.0f}M")
    print()

    if not test_mode:
        print("  Next steps:")
        print("    1. Train tokenizer (if needed)")
        print("    2. Start training")

    Sources = """
    Data from: https://huggingface.co/datasets/bigcode/starcoderdata
    Based on: https://huggingface.co/datasets/bigcode/the-stack
    """


if __name__ == "__main__":
    main()
